### ISSUE TITLE
LRX aircraft liveries appear to be broken - remove them if unfixable

### ISSUE THREAD

**Issue by NVB9ALT** [iuhairways/Liverychanger-modified#3]
When I tried using the 747-8 Lufthansa livery, I got the following error in the console: 
Cannot read properties of undefined (reading 'forEach')
If this bug is not fixable, please remove the affected liveries.
Also, it's worth noting that the A-10's solid gray livery appears under the A321Neo for some reason, and has the same issue as the LRX aircraft liveries. Moving the A-10 livery to under the A-10's listing in the aircraft menu may fix this, however.

**Comment by iuhairways** [comment]
i will remove them

**Comment by iuhairways** [comment]
done
